name: ud_grosir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  pinput: 2.2.11
  google_fonts: 3.0.1
  equatable: 2.0.3
  image_picker: 0.8.5+3
  firebase_storage: 10.3.1
  intl: 0.17.0
  badges: 2.0.3
  url_launcher: 6.1.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
